fix hack for batch size
llm-random/llm-random pull request #166
Opened 2023-08-17 12:05 UTC by kuba-krj

# Description
After refactors dataloaders return tuples, also loss is returned as tuple. I had to make changes that acount for it to make `hack_for_batch_size` work

# Checklist
Answer each question with "yes", and provide an explanation if the answer isn't what is expected.

1. Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - Answer: yes
2. Are all variables set with logical defaults that are backward compatible?
   - Answer: yes
3. Can you provide a link to a Neptune experiment verifying the functionality of this PR?
   - Answer: [Link to Neptune](https://app.neptune.ai/o/pmtest/org/llm-efficiency/runs/details?viewId=98a55dc0-aa23-4c1a-a622-93ec989d9ab3&detailsTab=charts&shortId=LLMEF-5801&type=run&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&query=%28%28%60sys%2Fowner%60%3Astring+%3D+%22kuba-krj%22%29%29)
4. Have you successfully executed the linter and tests?
   - Answer:yes
5. Are all functions concise and don't require splitting?
   - Answer:yes
6. Is there documentation for arguments and complex logic?
   - Answer:yes
7. Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - Answer:no tmp sols
8. Are all functions placed in appropriate files?
   - Answer:yes
9. Is the PR name meaningful and descriptive?
   - Answer:yes
10. Is PR description provided, or unnecessary?
    - Answer:provided
  
Other questions:

11. Have you not made changes to the requirements or anything related to the Singularity image? If you have, did you generate and upload a new image to the clusters?
    - Answer:no changes
12. Is the change significant enough to notify all individuals working with this repository?
    - Answer:no
13. Is there a need for a second reviewer?
    - Answer:no

2023-08-19 07:10 UTC, crewtool requested changes

2023-08-19 07:10 UTC, crewtool commented on research/conditional/utils/conditional_trainer.py
> +            tensor[1].data = tensor[1][:1].repeat(step + 1, 1).data
```suggestion
        for _cool_name_for_this, selfexplainatoryname in processed_batch:
            selfexplainatoryname.data = selfexplainatoryname[:1].repeat(step + 1, 1).data
```

2023-08-19 07:10 UTC, crewtool commented on research/conditional/utils/conditional_trainer.py
> +        )[0]
```suggestion
        loss, _aux_info = self._calculate_loss(
            batch=processed_batch,
            model=self.model,
            mixed_precision=self.mixed_precision,
            vocab_size=self.vocab_size,
        )
```

2023-08-23 09:15 UTC, maciek-pioro reviewed
Added a question about a change orthogonal to the main purpose of this PR. Also, I agree with @crewtool 's comments

2023-08-28 12:26 UTC, kuba-krj commented on research/conditional/utils/conditional_trainer.py
> +            ):
No, removing

2023-08-28 12:29 UTC, kuba-krj commented on research/conditional/utils/conditional_trainer.py
> +        )[0]
Right, changed

2023-08-28 12:59 UTC, Simontwice approved these changes

2023-08-28 13:00 UTC, merged