Refactor current baseline configs
llm-random/llm-random pull request #281
Opened 2023-11-06 16:36 UTC by ludziej

# Description
todo

# Checklist
   - [ ] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - [ ] Are all variables set with logical defaults that are backward compatible?
   - [ ] I attached link to neptune if it was necessary
   - [ ] Have you successfully executed the linter and tests?
   - [ ] Are all functions concise and don't require splitting?
   - [ ] Is there documentation for arguments and complex logic?
   - [ ] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - [ ] Are all functions placed in appropriate files?
   - [ ] Is the PR name meaningful and descriptive?
   - [ ] Is PR description provided, or unnecessary?
  
Other questions:
   - [ ] If I made changes to the requirements or anything related to the Singularity image I did generate new image and upload a new image to the clusters
   - [ ] If this change is significant enough I notified all individuals working with this repository (@channel in slack channel)
   - [ ] If there is a need for a second reviewer I requested additional review 

# Reviewer's checklist:
   - [ ] Does the Neptune link work and does it actually compare the situation before and after the PR?
   - [ ] Do I understand the code?
   - [ ] Do I think another reviewer is not needed or I commented that this PR need another reviewer?

2023-11-06 17:34 UTC, crewtool reviewed
Left comments

2023-11-06 17:34 UTC, crewtool commented on research/conditional/utils/argparse.py
> +    parser.add_argument("--effective_dff_x", type=int)
Could you provide explanations in 'help'?

2023-11-06 17:34 UTC, crewtool commented on research/conditional/train/configs/experiments/small_group.yaml
> +  dataset_type: wikibook  # TODO TYLKO TO JEST TEST REMOVE
debug leftovers

2023-11-06 17:34 UTC, crewtool commented on research/conditional/train/configs/baselines/common.yaml
> +  n_steps: 250_000
Why change?

2023-11-06 17:34 UTC, crewtool commented on lizrd/scripts/run_exp_remotely.sh
> +for i in "${@:2}"
Can you add a comment what is happening here, as none of us is an expert in bash ^^

2023-11-06 17:34 UTC, crewtool commented on research/conditional/train/configs/baselines/common.yaml
> +time: 1-00:00:00
Why change?

2023-11-06 17:34 UTC, crewtool commented on research/conditional/utils/model_utils.py
> +        dff_x = 4
This variable is a mystery to me. If it comes from the paper, maybe we can add a comment what it does above. If not, could we rename it?

2023-11-06 17:40 UTC, Simontwice requested changes
remove run_exp_remotely.sh changes

2023-11-06 17:46 UTC, Simontwice approved these changes
ok

2023-11-06 17:47 UTC, Simontwice requested changes
supply a script that will replace all the hashes in my local configs with the current ones

2023-11-06 17:52 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +  n_steps: 250_000
+1

2023-11-06 17:52 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +  n_steps: 250_000
revert

2023-11-06 17:53 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +  learning_rate: 1e-4
this should never be here

2023-11-06 17:53 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> -  final_lr_step: 250_000
revert

2023-11-06 17:56 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +name: "baseline"
the code is not supposed to support names outside "params"

2023-11-06 17:57 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +time: 1-00:00:00
+1, revert

2023-11-06 17:58 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +  learning_rate: 1e-4
revert

2023-11-06 18:02 UTC, Simontwice commented on lizrd/train/scheduler.py
> +            args.final_lr_step = args.n_steps
I do not agree with this code, it essentially introduces a default parameter for `final_lr_step`

2023-11-06 18:03 UTC, Simontwice commented on lizrd/scripts/grid.py
> +            config["params"]["name"] = config["name"]
revert, names should only be supplied in the "params" dict within configs.

2023-11-06 18:05 UTC, Simontwice requested changes
Baseline configs should stay the same (I support rearranging of arguments so it's consistent with other configs @ludziej, but some arguments that were added in `baselines/common.yaml` are unacceptable

2023-11-06 18:57 UTC, ludziej commented
applied PR comments, also added lizrd/scripts/list_md5sum.sh script that calculates all md5sums of our config yamls

2023-11-07 00:44 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> +  learning_rate: 1e-4
do not resolve, definitely revert

2023-11-07 00:45 UTC, Simontwice commented on research/conditional/train/configs/baselines/common.yaml
> -  final_lr_step: 250_000
why was this resolved. The final lr step is supposed to be 250K. the final training step is 275K. This line is required.

2023-11-07 00:47 UTC, Simontwice commented on lizrd/scripts/list_md5sum.sh
> +find $(dirname "$0")/../../research/conditional/train/configs/ -name '*.yaml' -type f -exec md5sum {} +
nice! thanks

2023-11-07 12:22 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/base.yaml
> +  learning_rate: 1e-4
revert, as discussed

2023-11-07 12:22 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/medium.yaml
> +  learning_rate: 1e-4
revert, as discussed

2023-11-07 12:22 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/mini.yaml
> +  learning_rate: 1e-4
revert, as discussed

2023-11-07 12:22 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/small.yaml
> +  learning_rate: 1e-4
revert, as discussed

2023-11-07 14:43 UTC, Simontwice commented on research/conditional/train/configs/experiments/medium.yaml
this file cannot be in the toplevel of directory `experiments`. Experiments should be divided into subdirectories, similar to `configs/baselines`. I would like to see directories `contmoe`,`expert_choice (or granularity)`, `misc`. 
I would like this experiments to go into `misc`.

2023-11-07 14:45 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/granularity/4/base.yaml
what does the name `4` name signify? It is not descriptive.

2023-11-07 14:48 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/base.yaml
If this file should be created, it should go to `configs/baselines/gpt/expert_choice/dense`.

2023-11-07 14:48 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/medium.yaml
If this file should be created, it should go to `configs/baselines/gpt/expert_choice/dense`.

2023-11-07 14:48 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/mini.yaml
If this file should be created, it should go to `configs/baselines/gpt/expert_choice/dense`.

2023-11-07 14:56 UTC, Simontwice requested changes
A few details left, some are my personal request w.r.t. the quality of our config structure:

1. I can only speak for the common part of the config structure, and there I did as good a job as I was able to. I cannot, however, give good feedback on the `expert_choice`/`granularity` configs, which is why I want @kuba-krj to accept this code as well. This way I can be sure that all of this code is up to standard.
2. [my request] Please move files `mini`,`small`,`medium`,`base` contained in `research/conditional/train/configs/baselines/gpt/*`, to a new created directory `research/conditional/train/configs/baselines/gpt/dense`. This will clear up the structure of our configs and make everything much more readable.
3. Address comments I left in this round of review.

I really appreciate this effort and the mutual feedback we've been exchanging.

2023-11-07 16:30 UTC, kuba-krj approved these changes
k

2023-11-07 16:39 UTC, Simontwice requested changes
All good! Please update the MD5 hashes and we're done! Thanks

2023-11-07 17:09 UTC, Simontwice commented on research/conditional/utils/argparse.py
> +    )  # not used by MoT & granularity
```suggestion
    )  # not used by granularity
```

2023-11-07 17:12 UTC, Simontwice approved these changes
LGTM, congrats

2023-11-07 17:58 UTC, merged