Logging in expert choice
llm-random/llm-random pull request #314
Opened 2023-11-24 21:14 UTC by ludziej

# Description
- Fixed heavy logging in expert choice
- More timing in expert choice
- Reduced one permute
- Fixed configs

# Checklist
   - [ ] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - [ ] Are all variables set with logical defaults that are backward compatible?
   - [ ] I attached link to neptune if it was necessary
   - [ ] Have you successfully executed the linter and tests?
   - [ ] Are all functions concise and don't require splitting?
   - [ ] Is there documentation for arguments and complex logic?
   - [ ] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - [ ] Are all functions placed in appropriate files?
   - [ ] Is the PR name meaningful and descriptive?
   - [ ] Is PR description provided, or unnecessary?
  
Other questions:
   - [ ] If I made changes to the requirements or anything related to the Singularity image I did generate new image and upload a new image to the clusters
   - [ ] If this change is significant enough I notified all individuals working with this repository (@channel in slack channel)
   - [ ] If there is a need for a second reviewer I requested additional review 

# Reviewer's checklist:
   - [ ] Does the Neptune link work and does it actually compare the situation before and after the PR?
   - [ ] Do I understand the code?
   - [ ] Do I think another reviewer is not needed or I commented that this PR need another reviewer?

2023-11-28 00:08 UTC, Simontwice commented on research/conditional/train/configs/baselines/gpt/dense/large.yaml
this calls for a separate PR

2023-11-28 00:10 UTC, Simontwice requested changes
Please review the comments

2023-11-28 10:47 UTC, ludziej commented on research/conditional/utils/layer_manager.py
> +                "expert_gating",
the thing is, here we need our another class "expert gating" not "expert choice" which is a submodule to be indexed by layer manager. This is primarly why heavy logging and time measuring did not work previously in Granular MoE - if class is not managed by layer manager, you cannot do any of these.

2023-11-28 10:54 UTC, ludziej commented on research/conditional/utils/layer_manager.py
> +                "expert_gating",
I think moving the list of "allowed" names to init should be a better solution.

2023-11-29 13:06 UTC, Simontwice commented on research/conditional/utils/layer_manager.py
> +                "expert_gating",
I understand now, thanks!

2023-11-29 13:07 UTC, Simontwice commented on research/conditional/utils/layer_manager.py
> +                "expert_gating",
I'm not sure whether we need to worry about such a refactor right now.

2023-11-29 13:08 UTC, Simontwice approved these changes
LGTM, but I'm no expert on expert choice

2023-11-29 15:25 UTC, merged