Implement Mamba
llm-random/llm-random pull request #337
Opened 2023-12-14 15:13 UTC by maciek-pioro

# Description
todo

# Checklist
   - [ ] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - [ ] Are all variables set with logical defaults that are backward compatible?
   - [ ] I attached link to neptune if it was necessary
   - [ ] Have you successfully executed the linter and tests?
   - [ ] Are all functions concise and don't require splitting?
   - [ ] Is there documentation for arguments and complex logic?
   - [ ] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - [ ] Are all functions placed in appropriate files?
   - [ ] Is the PR name meaningful and descriptive?
   - [ ] Is PR description provided, or unnecessary?
  
Other questions:
   - [ ] If I made changes to the requirements or anything related to the Singularity image I did generate new image and upload a new image to the clusters
   - [ ] If this change is significant enough I notified all individuals working with this repository (@channel in slack channel)
   - [ ] If there is a need for a second reviewer I requested additional review 

# Reviewer's checklist:
   - [ ] Does the Neptune link work and does it actually compare the situation before and after the PR?
   - [ ] Do I understand the code?
   - [ ] Do I think another reviewer is not needed or I commented that this PR need another reviewer?

2023-12-14 23:01 UTC, Krystian-Krol commented on sparsity-base.def
> +    apt-get -y install python3.10-venv git virtualenv python3-pip python3-dev libc++-15-dev libc++abi-15-dev wget curl
dlaczego już nie potrzeba `nvidia-cuda-toolkit`?

2023-12-14 23:16 UTC, Krystian-Krol requested changes
Ogarniam w miarę repo Mamby, więc chętnie pomogę przy tym mergu, trzeba to zrobić zupełnie inaczej - wziąć całego stacka od nich.

2023-12-14 23:16 UTC, Krystian-Krol commented on research/conditional/utils/model_utils.py
> +
tutaj else z raisem bo idę o zakład, że zapomnimy kiedyś ustawić `mamba_mode: vanilla`

2023-12-14 23:16 UTC, Krystian-Krol commented on research/conditional/train/cc_train.py
> +            block_modules[module_name] = get_mamba_layer(args)
tutaj else z raisem żeby łapać literówki

2023-12-14 23:16 UTC, Krystian-Krol commented on lizrd/train/train_utils.py
> +        block_modules,
TransformerTower nie ma takiej zmiennej

2023-12-14 23:16 UTC, Krystian-Krol commented on lizrd/train/train_utils.py
> +        block_modules,
Nie powinniśmy wpychać tutaj Mamby, powinniśmy korzystać z `MambaBlocków`, które są zopcone w ich repo

2023-12-15 09:45 UTC, maciek-pioro commented on lizrd/train/train_utils.py
> +        block_modules,
Imo nie jest to istotne, byłoby trochę szybsze, ale nie bardzo. Mogę zrobić test.

2023-12-19 11:25 UTC, Krystian-Krol reviewed
Nie wiem czy robienie folderu `mamba_dependencies` to dobry pomysł. Z grubsza to jest duplikacja kodu i zrobiłby się straszny syf gdybyśmy dla każdego projektu duplikowali tak. Nie mówiąc już o tym że zmiany teraz trzeba aplikować w dwóch miejscach.

Takim odpowiednikiem `main` brancha dla mamby może być `mamba` branch który będzie miał kompletnie zmodyfikowany obraz singularity (imo lepsze rozwiązanie). A ponieważ będziemy głównie modyfikować mambę to nie powinno być dużo ciężkich merge-conflictów rebase'ując ją okazjonalnie na maina

2023-12-19 11:25 UTC, Krystian-Krol commented on research/conditional/train/cc_train.py
> +    print(f"Number of learnable parameters: {n_learnable_parameters:_}")
`print` dla skryptu/debuga spoko, ale tutaj jakiś `log` byłby lepszy

2023-12-19 11:25 UTC, Krystian-Krol commented on research/conditional/train/cc_train.py
> +    print(
tutaj to samo

2023-12-19 15:19 UTC, Krystian-Krol approved these changes

2023-12-20 14:19 UTC, merged