Parallel MambaFF
llm-random/llm-random pull request #345
Opened 2024-01-07 15:39 UTC by Krystian-Krol

- Fix double residual
- Parallelise Mamba + FF

# Description
todo

# Checklist
   - [ ] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - [ ] Are all variables set with logical defaults that are backward compatible?
   - [ ] I attached link to neptune if it was necessary
   - [ ] Have you successfully executed the linter and tests?
   - [ ] Are all functions concise and don't require splitting?
   - [ ] Is there documentation for arguments and complex logic?
   - [ ] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - [ ] Are all functions placed in appropriate files?
   - [ ] Is the PR name meaningful and descriptive?
   - [ ] Is PR description provided, or unnecessary?
  
Other questions:
   - [ ] If I made changes to the requirements or anything related to the Singularity image I did generate new image and upload a new image to the clusters
   - [ ] If this change is significant enough I notified all individuals working with this repository (@channel in slack channel)
   - [ ] If there is a need for a second reviewer I requested additional review 

# Reviewer's checklist:
   - [ ] Does the Neptune link work and does it actually compare the situation before and after the PR?
   - [ ] Do I understand the code?
   - [ ] Do I think another reviewer is not needed or I commented that this PR need another reviewer?

2024-01-26 21:12 UTC, sebastianjaszczur commented on research/conditional/train/cc_train.py
> +            "parallel": lambda: Parallel(*[module() for module in modules])
I think this makes both blocks share the same layernorm. Maybe it's good, maybe it isn't; probably doesn't matter too much. But it's at least worth noting.

2024-01-26 21:13 UTC, sebastianjaszczur commented on research/conditional/train/cc_train.py
> +            "parallel": lambda: Parallel(*[module() for module in modules])
Intuitively, I would like both of those blocks to have separate layernorms, but I'm not sure.

2024-02-05 11:09 UTC, maciek-pioro commented on research/conditional/train/configs/experiments/expert_choice/mamba_parallel.yaml
Can we get rid of that?

2024-02-08 10:24 UTC, maciek-pioro commented on research/conditional/utils/model_utils.py
> +                llm.PreNormBlock, dmodel=args.dmodel, norm_class=torch.nn.Identity
Can we make e.g. `llm.ParallelPreNormBlock`? Now it looks like we have some part of the logic for creating a block in [`research/conditional/utils/model_utils.py`, `research/conditional/train/cc_train.py`] and another part in `lizrd/core/llm.py`, so basically it's split between `research` and `lizrd`, while actually it should reside in `lizrd`.

2024-02-08 10:25 UTC, maciek-pioro requested changes
Good job working on that! Can we make some adjustments to the structure of the code (info in the comment)?

2024-02-12 14:32 UTC, maciek-pioro approved these changes

2024-02-12 14:32 UTC, maciek-pioro commented
Nice, lgtm

2024-02-12 14:33 UTC, merged