Fix active param count
llm-random/llm-random pull request #462
Opened 2024-10-22 22:57 UTC by j321m

# Description
This pr fixes counting model parameters. Instead of getting count from torch model, it calculates from args using equations (brrr math). There are model configurations that aren't handled, in such case 1 is returned as model param count. This is because we don't want to kill new modules and 1 schould be strange enough to be recognised as wrong. Calculating from torch is still there and printed as sanity check. Main feature is fixing token to param ratio, and token_per_active x-axis on loss charts in neptune.

What I'm not sure about are the names of the new args variables, args that are logged to neptune. I tried to be descriptive, but shout out if sth is confusing.

# Checklist
   - [ ] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - [ ] Are all variables set with logical defaults that are backward compatible?
   - [ ] [I attached link to neptune if it was necessary](https://app.neptune.ai/o/pmtest/org/llm-random/runs/details?viewId=standard-view&detailsTab=metadata&shortId=LLMRANDOM-19203&type=run&compare=IwTgTADAzEA&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&query=((%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22param_count_fix_test%22)))
   - [ ] Have you successfully executed the linter and tests?
   - [ ] Are all functions concise and don't require splitting?
   - [ ] Is there documentation for arguments and complex logic?
   - [ ] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - [ ] Are all functions placed in appropriate files?
   - [ ] Is the PR name meaningful and descriptive?
   - [ ] Is PR description provided, or unnecessary?
  
Other questions:
   - [ ] If I made changes to the requirements or anything related to the Singularity image I did generate new image and upload a new image to the clusters
   - [ ] If this change is significant enough I notified all individuals working with this repository (@channel in slack channel)
   - [ ] If there is a need for a second reviewer I requested additional review 

# Reviewer's checklist:
   - [ ] Does the Neptune link work and does it actually compare the situation before and after the PR?
   - [ ] Do I understand the code?
   - [ ] Do I think another reviewer is not needed or I commented that this PR need another reviewer?

2024-10-24 10:58 UTC, madragonse requested changes
Generally, looks good, altho haven't checked the math

2024-10-24 10:58 UTC, madragonse commented on lizrd/support/misc.py
> +        )  # something that won't kill experiments, but is obviously not true
can you explain differently this result case?

2024-10-24 13:09 UTC, j321m commented on lizrd/support/logging.py
> +    # print(f"head_params: {head_params}")
ok

2024-10-25 13:06 UTC, madragonse commented
ty, approved

2024-10-29 12:31 UTC, merged